name: CI

on: push

permissions: {}

jobs:
  check:
    name: Use this action for check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Use this action
        id: report
        uses: ./
        with:
          modules: 'app'
          configuration: 'releaseRuntimeClasspath'
          repository: 'android/sunflower'
          before-sha: '13144ae9b1cb7a725dc846179cd8498058bafad2'
          after-sha: '8d000f6c72bc5384b4ca9f7452d620085919519d'
      - name: Show result
        run: echo '${{ steps.report.outputs.exists-diff }}'
